language: php
php:
  - '7.1'
services:
  - postgresql
before_script:
  # composer
  - composer install
  - composer dump-autoload
  # env
  - cp .env.travis .env
  # storage
  - ln -s storage/app/public public/storage
  # artisan
  - php artisan key:generate
  - php artisan config:clear
  - php artisan vendor:publish
  # pgsql
  - psql -c 'create database devopsclub_test;' -U postgres
  # migration
  - php artisan migrate
script: phpunit
